import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { ICONS_OUT_FILE } from '../constants.ts'
import { MATERIAL_ICONS } from './material.ts'
import { MUI_ICONS } from './mui.ts'
import { ICON_OVERRIDES } from './overrides.ts'

const ASSETS = join(import.meta.dirname, '../../node_modules/@phosphor-icons/core/assets')
const MASK = 'var(--matinee-icon) center / contain no-repeat'

function svgFile(icon: string): string {
  const [name, weight = 'regular'] = icon.split(':')
  return weight === 'regular'
    ? join(ASSETS, 'regular', `${name}.svg`)
    : join(ASSETS, weight, `${name}-${weight}.svg`)
}

function variable(icon: string): string {
  return `--matinee-i-${icon.replace(':', '-')}`
}

function dataUri(svg: string): string {
  const body = svg
    .trim()
    .replace(' fill="currentColor"', '')
    .replaceAll('"', '\'')
    .replace(/[<>#%]/g, encodeURIComponent)
  return `url("data:image/svg+xml,${body}")`
}

function groupByIcon(entries: [string, string][]): Map<string, string[]> {
  const groups = new Map<string, string[]>()
  for (const [selector, icon] of entries)
    groups.set(icon, [...(groups.get(icon) ?? []), selector])
  return groups
}

const legacy: [string, string][] = Object.entries(MATERIAL_ICONS).map(([name, icon]) => [`.material-icons.${name}`, icon])
const mui: [string, string][] = Object.entries(MUI_ICONS).map(([name, icon]) => [`.MuiSvgIcon-root[data-testid='${name}Icon']`, icon])
const overrides: [string, string][] = ICON_OVERRIDES.map(({ selector, icon }) => [selector, icon])
const all = [...legacy, ...mui, ...overrides]

const icons = [...new Set(all.map(([, icon]) => icon))].sort()
const missing = icons.filter(icon => !existsSync(svgFile(icon)))
if (missing.length)
  throw new Error(`Unknown Phosphor icons: ${missing.join(', ')}`)

const css = [
  '/* Generated by scripts/icons/generate.ts from @phosphor-icons/core (MIT). Do not edit. */',
  '',
  ':root {',
  ...icons.map(icon => `  ${variable(icon)}: ${dataUri(readFileSync(svgFile(icon), 'utf8'))};`),
  '}',
  '',
  ...[...groupByIcon(all)].map(([icon, selectors]) => `${selectors.join(',\n')} {\n  --matinee-icon: var(${variable(icon)});\n}\n`),
  `:is(${legacy.map(([s]) => s).join(', ')})::before {`,
  '  content: \'\';',
  '  display: block;',
  '  width: 1em;',
  '  height: 1em;',
  '  background-color: currentColor;',
  `  mask: ${MASK};`,
  '}',
  '',
  `:is(${mui.map(([s]) => s).join(', ')}) {`,
  '  background-color: currentColor;',
  `  mask: ${MASK};`,
  '}',
  '',
  `:is(${mui.map(([s]) => s).join(', ')}) > * {`,
  '  visibility: hidden;',
  '}',
  '',
].join('\n')

mkdirSync(dirname(ICONS_OUT_FILE), { recursive: true })
writeFileSync(ICONS_OUT_FILE, css)
console.log(`Wrote ${icons.length} icons to ${ICONS_OUT_FILE}`)
