import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname } from 'node:path'
import { ICON_FONT_NAME, ICON_FONT_OUT_FILE, ICONS_OUT_FILE } from '../constants.ts'
import { missingIcons, readIcon } from './assets.ts'
import { buildIconFont } from './font.ts'
import { MATERIAL_ICONS } from './material.ts'
import { MUI_ICONS } from './mui.ts'
import { ICON_OVERRIDES } from './overrides.ts'
import { PLUGIN_ICONS } from './plugins.ts'

const MASK = 'var(--matinee-icon) center / contain no-repeat'

function variable(icon: string): string {
  return `--matinee-i-${icon.replace(':', '-')}`
}

function dataUri(svg: string): string {
  const body = svg
    .trim()
    .replace(' fill="currentColor"', '')
    .replaceAll('"', '\'')
    .replace(/[<>#%]/g, encodeURIComponent)
  return `url("data:image/svg+xml,${body}")`
}

function groupByIcon(entries: [string, string][]): Map<string, string[]> {
  const groups = new Map<string, string[]>()
  for (const [selector, icon] of entries)
    groups.set(icon, [...(groups.get(icon) ?? []), selector])
  return groups
}

const legacy: [string, string][] = Object.entries(MATERIAL_ICONS).map(([name, icon]) => [`.material-icons.${name}`, icon])
const mui: [string, string][] = Object.entries(MUI_ICONS).map(([name, icon]) => [`.MuiSvgIcon-root[data-testid='${name}Icon']`, icon])
const overrides: [string, string][] = ICON_OVERRIDES.map(({ selector, icon }) => [selector, icon])
const all = [...legacy, ...mui, ...overrides]

const ligatures = { ...MATERIAL_ICONS, ...PLUGIN_ICONS }
const icons = [...new Set(all.map(([, icon]) => icon))].sort()
const missing = missingIcons([...icons, ...Object.values(ligatures)])
if (missing.length)
  throw new Error(`Unknown Phosphor icons: ${missing.join(', ')}`)

const css = [
  '/* Generated by scripts/icons/generate.ts from @phosphor-icons/core (MIT). Do not edit. */',
  '',
  ':root {',
  ...icons.map(icon => `  ${variable(icon)}: ${dataUri(readIcon(icon))};`),
  '}',
  '',
  ...[...groupByIcon(all)].map(([icon, selectors]) => `${selectors.join(',\n')} {\n  --matinee-icon: var(${variable(icon)});\n}\n`),
  `:is(${legacy.map(([s]) => s).join(', ')})::before {`,
  '  content: \'\';',
  '  display: block;',
  '  width: 1em;',
  '  height: 1em;',
  '  background-color: currentColor;',
  `  mask: ${MASK};`,
  '}',
  '',
  `:is(${mui.map(([s]) => s).join(', ')}) {`,
  '  background-color: currentColor;',
  `  mask: ${MASK};`,
  '}',
  '',
  `:is(${mui.map(([s]) => s).join(', ')}) > * {`,
  '  visibility: hidden;',
  '}',
  '',
].join('\n')

const font = await buildIconFont(ligatures, ICON_FONT_NAME)
const fontCss = [
  '/* Generated by scripts/icons/generate.ts. Phosphor glyphs (MIT) behind Material icon ligature names. Do not edit. */',
  '',
  '@font-face {',
  `  font-family: '${ICON_FONT_NAME}';`,
  '  font-style: normal;',
  '  font-weight: 400;',
  '  font-display: block;',
  `  src: url('data:font/woff2;base64,${font.toString('base64')}') format('woff2');`,
  '}',
  '',
  '/* Icons written as text (<i class="material-icons">settings</i>) resolve through the ligature font; anything it lacks falls back to Material. */',
  '.material-icons {',
  `  font-family: '${ICON_FONT_NAME}', 'Material Icons';`,
  '}',
  '',
].join('\n')

mkdirSync(dirname(ICONS_OUT_FILE), { recursive: true })
writeFileSync(ICONS_OUT_FILE, css)
writeFileSync(ICON_FONT_OUT_FILE, fontCss)
console.log(`Wrote ${icons.length} icons to ${ICONS_OUT_FILE} and ${Object.keys(ligatures).length} ligatures (${font.length} bytes) to ${ICON_FONT_OUT_FILE}`)
